#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path


# ── Color helpers ─────────────────────────────────────────────────────────────

def hex_to_rgb(h: str) -> tuple[float, float, float]:
    """Parse a 6-digit hex color string to (r, g, b) floats in [0, 1]."""
    h = h.lstrip("#")
    if len(h) != 6:
        raise ValueError(f"Expected 6-digit hex color, got: '{h}'")
    r = int(h[0:2], 16) / 255.0
    g = int(h[2:4], 16) / 255.0
    b = int(h[4:6], 16) / 255.0
    return r, g, b


def srgb_to_linear(c: float) -> float:
    """sRGB gamma → linear light (IEC 61966-2-1)."""
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def linear_to_srgb(c: float) -> float:
    """Linear light → sRGB gamma (IEC 61966-2-1), clamped to [0, 1]."""
    c = max(0.0, min(1.0, c))
    return c * 12.92 if c <= 0.0031308 else 1.055 * (c ** (1.0 / 2.4)) - 0.055


def to_linear_rgb(
    r: float, g: float, b: float
) -> tuple[float, float, float]:
    return srgb_to_linear(r), srgb_to_linear(g), srgb_to_linear(b)


# ── Nearest-color lookup ──────────────────────────────────────────────────────

def preprocess_palette(
    palette_rgb: list[tuple[float, float, float]], use_linear: bool
) -> list[tuple[float, float, float, float, float, float]]:
    """
    Return palette as tuples of (sRGB_r, sRGB_g, sRGB_b, cmp_r, cmp_g, cmp_b)
    where cmp_* are the values used for distance comparison.
    Precomputing avoids repeating the conversion inside the hot loop.
    """
    result = []
    for sr, sg, sb in palette_rgb:
        if use_linear:
            cr, cg, cb = to_linear_rgb(sr, sg, sb)
        else:
            cr, cg, cb = sr, sg, sb
        result.append((sr, sg, sb, cr, cg, cb))
    return result


def nearest_palette_color(
    r: float, g: float, b: float,
    palette_preprocessed: list[tuple[float, float, float, float, float, float]],
    use_linear: bool,
) -> tuple[float, float, float]:
    """Return the palette color closest to (r, g, b) in the chosen color space."""
    if use_linear:
        cr, cg, cb = to_linear_rgb(r, g, b)
    else:
        cr, cg, cb = r, g, b

    best_sr, best_sg, best_sb = palette_preprocessed[0][:3]
    best_dist = float("inf")

    for sr, sg, sb, pr, pg, pb in palette_preprocessed:
        dist = (cr - pr) ** 2 + (cg - pg) ** 2 + (cb - pb) ** 2
        if dist < best_dist:
            best_dist = dist
            best_sr, best_sg, best_sb = sr, sg, sb

    return best_sr, best_sg, best_sb


# ── LUT construction ──────────────────────────────────────────────────────────

def build_lut_entries(
    size: int,
    palette_rgb: list[tuple[float, float, float]],
    use_linear: bool = False,
) -> list[tuple[float, float, float]]:
    """
    Build the full list of output (R, G, B) entries for a size³ 3D LUT.

    Iteration order follows the .cube standard:
        R varies fastest  (inner loop)
        G varies second
        B varies slowest  (outer loop)

    This means entry index = r_i + g_i * size + b_i * size²
    """
    palette_pre = preprocess_palette(palette_rgb, use_linear)
    n = size - 1  # normalisation denominator
    entries: list[tuple[float, float, float]] = []

    total = size ** 3
    milestone = max(1, total // 10)

    for b_i in range(size):
        for g_i in range(size):
            for r_i in range(size):
                r, g, b = r_i / n, g_i / n, b_i / n
                out = nearest_palette_color(r, g, b, palette_pre, use_linear)
                entries.append(out)

            # Progress feedback every ~10 %
            done = b_i * size * size + (g_i + 1) * size
            if done % milestone < size:
                pct = int(done / total * 100)
                print(f"  {pct:3d}%", end="\r", flush=True)

    print("  100%")
    return entries


# ── .cube writer ──────────────────────────────────────────────────────────────

def write_cube(
    path: Path,
    entries: list[tuple[float, float, float]],
    size: int,
    title: str = "Lospec Palette LUT",
) -> None:
    """
    Write an Adobe .cube 3D LUT file.

    Format spec: https://wwwimages2.adobe.com/content/dam/acom/en/products/
                 speedgrade/cc/pdfs/cube-lut-specification-1.0.pdf

    Values are floating-point in [0.0, 1.0].  Six decimal places gives
    sub-1/1000000 precision — more than enough for 8-bit palette colors
    (whose exact values are multiples of 1/255 ≈ 0.003922).
    """
    with open(path, "w", encoding="utf-8") as f:
        f.write(f'TITLE "{title}"\n')
        f.write(f"# Generated by lospec2lut.py\n")
        f.write(f"# Palette-snapping LUT: every input color mapped to\n")
        f.write(f"# its nearest palette color.\n")
        f.write(f"\n")
        f.write(f"LUT_3D_SIZE {size}\n")
        f.write(f"DOMAIN_MIN 0.0 0.0 0.0\n")
        f.write(f"DOMAIN_MAX 1.0 1.0 1.0\n")
        f.write(f"\n")
        for r, g, b in entries:
            f.write(f"{r:.6f} {g:.6f} {b:.6f}\n")


# ── .3dl writer ───────────────────────────────────────────────────────────────

def write_3dl(
    path: Path,
    entries: list[tuple[float, float, float]],
    size: int,
    bit_depth: int = 12,
    title: str = "Lospec Palette LUT",
) -> None:
    """
    Write an Autodesk/Lustre .3dl 3D LUT file.

    Format:
      Line 1..N of header: space-separated integer mesh (input) values.
      Then one "R G B" integer triplet per LUT entry (same order as .cube).

    Bit depths and their integer ranges:
      10-bit: 0 – 1023
      12-bit: 0 – 4095   (default, matches Resolve's preferred .3dl)
      16-bit: 0 – 65535

    The mesh values mark where each axis sample falls in code-value space.
    For a uniform LUT they are evenly spaced from 0 to max_val.
    """
    max_val = (1 << bit_depth) - 1
    mesh_vals = [round(i * max_val / (size - 1)) for i in range(size)]

    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# {title}\n")
        f.write(f"# Generated by lospec2lut.py\n")
        f.write(f"# 3DL format | {bit_depth}-bit | size {size}\n")
        f.write(f"\n")
        # Mesh header: input code values for each axis
        f.write(" ".join(str(v) for v in mesh_vals) + "\n")
        f.write(f"\n")
        for r, g, b in entries:
            ri = round(r * max_val)
            gi = round(g * max_val)
            bi = round(b * max_val)
            f.write(f"{ri} {gi} {bi}\n")


# ── Lospec API ────────────────────────────────────────────────────────────────

LOSPEC_API_URL = "https://lospec.com/palette-list/{slug}.json"


def fetch_lospec_palette(slug: str) -> dict:
    """
    Fetch palette data from the Lospec JSON API.

    Returns a dict with keys: name, author, colors (list of hex strings).
    Exits with an error message on network failure or missing palette.
    """
    url = LOSPEC_API_URL.format(slug=slug)
    print(f"Fetching: {url}")
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "lospec2lut/1.0"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        if e.code == 404:
            print(f"Error: Palette '{slug}' not found on Lospec.", file=sys.stderr)
        else:
            print(f"HTTP error {e.code} fetching '{slug}'.", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error fetching palette: {e}", file=sys.stderr)
        sys.exit(1)

    if "error" in data:
        print(f"Lospec error: {data['error']}", file=sys.stderr)
        sys.exit(1)

    return data


def parse_hex_string(hex_str: str) -> list[tuple[float, float, float]]:
    """Parse a space- or comma-separated string of hex colors."""
    tokens = hex_str.replace(",", " ").split()
    try:
        return [hex_to_rgb(t) for t in tokens]
    except ValueError as e:
        print(f"Error parsing hex colors: {e}", file=sys.stderr)
        sys.exit(1)


# ── CLI ───────────────────────────────────────────────────────────────────────

VALID_SIZES = [17, 33, 65]
VALID_FORMATS = ["cube", "3dl", "both"]
VALID_BIT_DEPTHS = [10, 12, 16]


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="lospec2lut.py",
        description="Convert a Lospec palette to a 3D LUT (.cube / .3dl).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
examples:
  python lospec2lut.py resurrect-64
  python lospec2lut.py lospec500 --size 65 --format both
  python lospec2lut.py nintendo-gameboy-bgb --format 3dl --bit-depth 12
  python lospec2lut.py my-pal --hex "9bbc0f 8bac0f 306230 0f380f"
  python lospec2lut.py resurrect-64 --linear --output ./luts/
        """,
    )

    parser.add_argument(
        "slug",
        help='Lospec palette slug (the URL slug, e.g. "resurrect-64"). '
             "Also used as the output filename stem when --hex is provided.",
    )
    parser.add_argument(
        "--size",
        type=int,
        choices=VALID_SIZES,
        default=33,
        metavar="{17,33,65}",
        help="LUT grid size N (produces N³ entries). Default: 33",
    )
    parser.add_argument(
        "--format",
        choices=VALID_FORMATS,
        default="cube",
        help="Output format. 'both' writes .cube and .3dl. Default: cube",
    )
    parser.add_argument(
        "--bit-depth",
        type=int,
        choices=VALID_BIT_DEPTHS,
        default=12,
        metavar="{10,12,16}",
        help="Integer bit depth for .3dl output. Default: 12",
    )
    parser.add_argument(
        "--hex",
        type=str,
        default=None,
        metavar="COLORS",
        help="Provide palette colors directly as hex values, bypassing the "
             'Lospec API. Example: --hex "ff0000 00ff00 0000ff"',
    )
    parser.add_argument(
        "--linear",
        action="store_true",
        help="Use linear-light (perceptually uniform) distance for "
             "nearest-color matching instead of sRGB distance.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=".",
        metavar="PATH",
        help="Output directory or file path (without extension). Default: '.'",
    )

    args = parser.parse_args(argv)

    # ── Acquire palette ───────────────────────────────────────────────────────
    if args.hex:
        palette_rgb = parse_hex_string(args.hex)
        palette_title = args.slug
        print(f"Using {len(palette_rgb)} directly-provided colors.")
    else:
        data = fetch_lospec_palette(args.slug)
        palette_title = data.get("name", args.slug)
        palette_rgb = [hex_to_rgb(h) for h in data["colors"]]
        print(f"  Name   : {palette_title}")
        print(f"  Author : {data.get('author', 'unknown')}")
        print(f"  Colors : {len(palette_rgb)}")

    if len(palette_rgb) < 2:
        print("Error: palette must have at least 2 colors.", file=sys.stderr)
        sys.exit(1)

    # ── Print palette swatch ──────────────────────────────────────────────────
    hex_preview = "  ".join(
        "#{:02x}{:02x}{:02x}".format(
            round(r * 255), round(g * 255), round(b * 255)
        )
        for r, g, b in palette_rgb[:12]
    )
    suffix = f"  … (+{len(palette_rgb) - 12} more)" if len(palette_rgb) > 12 else ""
    print(f"  Swatch : {hex_preview}{suffix}")

    # ── Build LUT ─────────────────────────────────────────────────────────────
    metric = "linear-light" if args.linear else "sRGB"
    print(
        f"\nBuilding {args.size}³ = {args.size**3:,} LUT entries "
        f"({metric} distance) …"
    )
    entries = build_lut_entries(args.size, palette_rgb, args.linear)

    # ── Resolve output path ───────────────────────────────────────────────────
    out = Path(args.output)
    if out.suffix in (".cube", ".3dl"):
        # User passed a full file path — use as stem
        base = out.with_suffix("")
        base.parent.mkdir(parents=True, exist_ok=True)
    else:
        # Treat as directory
        out.mkdir(parents=True, exist_ok=True)
        base = out / args.slug

    # ── Write files ───────────────────────────────────────────────────────────
    formats = ["cube", "3dl"] if args.format == "both" else [args.format]
    print()
    for fmt in formats:
        if fmt == "cube":
            dst = base.with_suffix(".cube")
            write_cube(dst, entries, args.size, palette_title)
            print(f"  Written : {dst}")
            print(f"            CUBE format | size {args.size} | {args.size**3:,} entries")
        elif fmt == "3dl":
            dst = base.with_suffix(".3dl")
            write_3dl(dst, entries, args.size, args.bit_depth, palette_title)
            print(f"  Written : {dst}")
            print(
                f"            3DL format | size {args.size} | "
                f"{args.bit_depth}-bit | {args.size**3:,} entries"
            )

    print("\nDone.")


if __name__ == "__main__":
    main()
